# Generated by Django 3.2.16 on 2023-04-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotukotu', '0002_alter_users_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(error_messages={'unique': 'このメールアドレスは既に使用されています。'}, max_length=255, unique=True),
        ),
    ]
